POST http://localhost:3001/update
Content-Type: application/json

{
    "isopen" : false,
    "path" : "sacjsc",
    "tennganhang" : "231232132131233",
    "sotaikhoan" : "213123123",
    "sotiennhan" : "a123123"
}
